[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = [
  "mkdir -p /usr/local/bin && echo '#!/bin/sh' > /usr/local/bin/husky && echo 'exit 0' >> /usr/local/bin/husky && chmod +x /usr/local/bin/husky && npm install"
]

[start]
cmd = "node index.js"
