[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = [
  "mkdir -p /usr/local/bin && printf '#!/bin/sh\nexit 0\n' > /usr/local/bin/husky && chmod +x /usr/local/bin/husky && npm install"
]

[start]
cmd = "node index.js"
